---
title: "exvivo"
output: html_document
date: "2024-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load libraries
```{r}
library(dplyr)
library(tidyr)
library(tibble)
library(stringr)
library(ggplot2)
library(vegan)
library(ggsci)
library(ggthemes)
library(patchwork)
library(ggpubr)
library(ggforce)
library(ape)
library(pheatmap)
library(phyloseq)
library(Maaslin2)
library(ComplexHeatmap)
library(circlize)
library(UpSetR)
```



# import data
```{r}
df_profile <- read.delim("metaphlan/merged_abundance_table_species.txt", check.names = FALSE)
metadata <- read.csv("metaphlan/metadata.csv")
metadata <- metadata %>% filter(metadata$Samples %in% colnames(df_profile)) %>%
              filter(Mice == "IBD")
rownames(metadata) <- metadata$Samples

df_profile <- df_profile[, c("clade_name", metadata$Samples)]
df_profile <- df_profile[rowSums(df_profile[,2:ncol(df_profile)])>0, ]
dim(df_profile)
```


# inspect microbial composition
```{r}
################################################################################
# Phylum level
################################################################################
df_profile_p <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_p$clade_name <- str_extract(df_profile_p$clade_name, "p__[^|]+")
df_profile_p <- aggregate(.~clade_name, df_profile_p, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")

# visualization
df_profile_p_melt <- reshape2::melt(df_profile_p, id="clade_name")
df_profile_p_melt_m <- merge(df_profile_p_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_p_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_p_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_p_melt_mean$Peptide <- factor(df_profile_p_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_p_melt_mean$Concentration <- as.character(df_profile_p_melt_mean$Concentration)
df_profile_p_melt_mean$Concentration <- factor(df_profile_p_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_p_melt_mean$clade_name <- factor(df_profile_p_melt_mean$clade_name,
                                            levels = c("p__Proteobacteria", "p__Firmicutes", "p__Bacteroidota",
                                                       "p__Actinobacteria",  "p__Deferribacteres",
                                                       "p__Candidatus_Melainabacteria", "p__Candidatus_Saccharibacteria", "p__Tenericutes",
                                                       "p__Bacteria_unclassified"))
p_phylum <- ggplot(data = df_profile_p_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_d3("category20")+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Phylum")+
            theme(axis.text.x = element_text(colour = "black"))

################################################################################
# Class level
################################################################################
df_profile_c <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_c$clade_name <- str_extract(df_profile_c$clade_name, "c__[^|]+")
df_profile_c <- aggregate(.~clade_name, df_profile_c, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")
top10_taxa <- df_profile_c$clade_name[order(rowSums(df_profile_c[,2:ncol(df_profile_c)]), decreasing = TRUE)][1:10]
df_profile_c <- df_profile_c %>% filter(clade_name %in% top10_taxa)
df_profile_c[nrow(df_profile_c) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_c[,2:ncol(df_profile_c)])))
df_profile_c[,2:ncol(df_profile_c)] <- lapply(df_profile_c[,2:ncol(df_profile_c)], as.numeric)

# visualization
df_profile_c_melt <- reshape2::melt(df_profile_c, id="clade_name")
df_profile_c_melt_m <- merge(df_profile_c_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_c_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_c_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_c_melt_mean$Peptide <- factor(df_profile_c_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_c_melt_mean$Concentration <- as.character(df_profile_c_melt_mean$Concentration)
df_profile_c_melt_mean$Concentration <- factor(df_profile_c_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_c_melt_mean$clade_name <- factor(df_profile_c_melt_mean$clade_name,
                                            levels = c(top10_taxa, "Others"))
p_class <- ggplot(data = df_profile_c_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_d3("category20")+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Class")+
            theme(axis.text.x = element_text(colour = "black"))

################################################################################
# Order level
################################################################################
df_profile_o <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_o$clade_name <- str_extract(df_profile_o$clade_name, "o__[^|]+")
df_profile_o <- aggregate(.~clade_name, df_profile_o, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")
top10_taxa <- df_profile_o$clade_name[order(rowSums(df_profile_o[,2:ncol(df_profile_o)]), decreasing = TRUE)][1:10]
df_profile_o <- df_profile_o %>% filter(clade_name %in% top10_taxa)
df_profile_o[nrow(df_profile_o) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_o[,2:ncol(df_profile_o)])))
df_profile_o[,2:ncol(df_profile_o)] <- lapply(df_profile_o[,2:ncol(df_profile_o)], as.numeric)

# visualization
df_profile_o_melt <- reshape2::melt(df_profile_o, id="clade_name")
df_profile_o_melt_m <- merge(df_profile_o_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_o_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_o_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_o_melt_mean$Peptide <- factor(df_profile_o_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_o_melt_mean$Concentration <- as.character(df_profile_o_melt_mean$Concentration)
df_profile_o_melt_mean$Concentration <- factor(df_profile_o_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_o_melt_mean$clade_name <- factor(df_profile_o_melt_mean$clade_name,
                                            levels = c(top10_taxa, "Others"))
p_order <- ggplot(data = df_profile_o_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_d3("category20")+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Order")+
            theme(axis.text.x = element_text(colour = "black"))

################################################################################
# Family level
################################################################################
df_profile_f <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_f$clade_name <- str_extract(df_profile_f$clade_name, "f__[^|]+")
df_profile_f <- aggregate(.~clade_name, df_profile_f, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")
top10_taxa <- df_profile_f$clade_name[order(rowSums(df_profile_f[,2:ncol(df_profile_f)]), decreasing = TRUE)][1:10]
df_profile_f <- df_profile_f %>% filter(clade_name %in% top10_taxa)
df_profile_f[nrow(df_profile_f) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_f[,2:ncol(df_profile_f)])))
df_profile_f[,2:ncol(df_profile_f)] <- lapply(df_profile_f[,2:ncol(df_profile_f)], as.numeric)

# visualization
df_profile_f_melt <- reshape2::melt(df_profile_f, id="clade_name")
df_profile_f_melt_m <- merge(df_profile_f_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_f_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_f_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_f_melt_mean$Peptide <- factor(df_profile_f_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_f_melt_mean$Concentration <- as.character(df_profile_f_melt_mean$Concentration)
df_profile_f_melt_mean$Concentration <- factor(df_profile_f_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_f_melt_mean$clade_name <- factor(df_profile_f_melt_mean$clade_name,
                                            levels = c(top10_taxa, "Others"))
p_family <- ggplot(data = df_profile_f_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_d3("category20")+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Family")+
            theme(axis.text.x = element_text(colour = "black"))

################################################################################
# Genus level
################################################################################
df_profile_g <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_g$clade_name <- str_extract(df_profile_g$clade_name, "g__[^|]+")
df_profile_g <- aggregate(.~clade_name, df_profile_g, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")
top10_taxa <- df_profile_g$clade_name[order(rowSums(df_profile_g[,2:ncol(df_profile_g)]), decreasing = TRUE)][1:10]
df_profile_g <- df_profile_g %>% filter(clade_name %in% top10_taxa)
df_profile_g[nrow(df_profile_g) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_g[,2:ncol(df_profile_g)])))
df_profile_g[,2:ncol(df_profile_g)] <- lapply(df_profile_g[,2:ncol(df_profile_g)], as.numeric)

# visualization
df_profile_g_melt <- reshape2::melt(df_profile_g, id="clade_name")
df_profile_g_melt_m <- merge(df_profile_g_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_g_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_g_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_g_melt_mean$Peptide <- factor(df_profile_g_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_g_melt_mean$Concentration <- as.character(df_profile_g_melt_mean$Concentration)
df_profile_g_melt_mean$Concentration <- factor(df_profile_g_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_g_melt_mean$clade_name <- factor(df_profile_g_melt_mean$clade_name,
                                            levels = c(top10_taxa, "Others"))
p_genus <- ggplot(data = df_profile_g_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_d3("category20")+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Genus")+
            theme(axis.text.x = element_text(colour = "black"))

################################################################################
# Species level
################################################################################
df_profile_s <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_s$clade_name <- str_extract(df_profile_s$clade_name, "s__[^|]+")
df_profile_s <- aggregate(.~clade_name, df_profile_s, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")
top10_taxa <- df_profile_s$clade_name[order(rowSums(df_profile_s[,2:ncol(df_profile_s)]), decreasing = TRUE)][1:10]
df_profile_s <- df_profile_s %>% filter(clade_name %in% top10_taxa)
df_profile_s[nrow(df_profile_s) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_s[,2:ncol(df_profile_s)])))
df_profile_s[,2:ncol(df_profile_s)] <- lapply(df_profile_s[,2:ncol(df_profile_s)], as.numeric)

# visualization
df_profile_s_melt <- reshape2::melt(df_profile_s, id="clade_name")
df_profile_s_melt_m <- merge(df_profile_s_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_s_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_s_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_s_melt_mean$Peptide <- factor(df_profile_s_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_s_melt_mean$Concentration <- as.character(df_profile_s_melt_mean$Concentration)
df_profile_s_melt_mean$Concentration <- factor(df_profile_s_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_s_melt_mean$clade_name <- factor(df_profile_s_melt_mean$clade_name,
                                            levels = c(top10_taxa, "Others"))
p_species <- ggplot(data = df_profile_s_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_d3("category20")+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Species")+
            theme(axis.text.x = element_text(colour = "black"))

## Combine figures
pp <- p_phylum / p_class / p_order / p_family / p_genus / p_species

ggsave("figures/Barplot_Relative_abundance.pdf", pp, width = 14, height = 20)



# plot family level seperately
df_profile_f <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_f$clade_name <- str_extract(df_profile_f$clade_name, "f__[^|]+")
df_profile_f <- aggregate(.~clade_name, df_profile_f, sum)
top20_taxa <- df_profile_f$clade_name[order(rowSums(df_profile_f[,2:ncol(df_profile_f)]), decreasing = TRUE)][1:20]
df_profile_f <- df_profile_f %>% filter(clade_name %in% top20_taxa)
df_profile_f[nrow(df_profile_f) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_f[,2:ncol(df_profile_f)])))
df_profile_f[,2:ncol(df_profile_f)] <- lapply(df_profile_f[,2:ncol(df_profile_f)], as.numeric)

# visualization
df_profile_f_melt <- reshape2::melt(df_profile_f, id="clade_name")
df_profile_f_melt_m <- merge(df_profile_f_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
df_profile_f_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
                                    df_profile_f_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
                                    mean)
df_profile_f_melt_mean$Peptide <- factor(df_profile_f_melt_mean$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_f_melt_mean$Concentration <- as.character(df_profile_f_melt_mean$Concentration)
df_profile_f_melt_mean$Concentration <- factor(df_profile_f_melt_mean$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_f_melt_mean$clade_name <- factor(df_profile_f_melt_mean$clade_name,
                                            levels = c(top20_taxa, "Others"))
p_family <- ggplot(data = df_profile_f_melt_mean, aes(x = Concentration, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide, scales = "free", space = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_igv()+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Family")+
            theme(axis.text.x = element_text(colour = "black"))
ggsave("figures/Barplot_Relative_abundance_Family_level.pdf", p_family, width = 9, height = 4)
```



# plot genus level
```{r}
################################################################################
# Genus level
################################################################################
df_profile_g <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_g$clade_name <- str_extract(df_profile_g$clade_name, "g__[^|]+")
df_profile_g <- aggregate(.~clade_name, df_profile_g, sum)
# df_profile_p <- df_profile_p %>% remove_rownames %>% column_to_rownames(var="clade_name")
top20_taxa <- df_profile_g$clade_name[order(rowSums(df_profile_g[,2:ncol(df_profile_g)]), decreasing = TRUE)][1:20]
df_profile_g <- df_profile_g %>% filter(clade_name %in% top20_taxa)
df_profile_g[nrow(df_profile_g) + 1,] <- c("Others", as.vector(100 - colSums(df_profile_g[,2:ncol(df_profile_g)])))
df_profile_g[,2:ncol(df_profile_g)] <- lapply(df_profile_g[,2:ncol(df_profile_g)], as.numeric)

# visualization
df_profile_g_melt <- reshape2::melt(df_profile_g, id="clade_name")
df_profile_g_melt_m <- merge(df_profile_g_melt, metadata, by.x = "variable", by.y = "Samples", all.x = TRUE)
# df_profile_g_melt_mean <- aggregate(value~clade_name + Peptide + Concentration, 
#                                     df_profile_g_melt_m[,c("clade_name", "value", "Peptide", "Concentration")],
#                                     mean)
df_profile_g_melt_m$Peptide <- factor(df_profile_g_melt_m$Peptide,
                                            levels=c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_profile_g_melt_m$Concentration <- as.character(df_profile_g_melt_m$Concentration)
df_profile_g_melt_m$Concentration <- factor(df_profile_g_melt_m$Concentration,
                                               levels = c("0.1", "1", "10"))
df_profile_g_melt_m$clade_name <- factor(df_profile_g_melt_m$clade_name,
                                            levels = c(top20_taxa, "Others"))
p_genus <- ggplot(data = df_profile_g_melt_m, aes(x = variable, y = value)) +
            geom_bar(aes(fill = clade_name), stat = "identity")+
            #geom_alluvium(aes(fill = clade_name), color="black", alpha = 1, decreasing = FALSE) +
            facet_grid(. ~ Peptide + Concentration, scales = "free")+
            # geom_flow(stat = "alluvium", lode.guidance = "frontback")+
            theme_bw() +
            # scale_fill_manual(values = c25)+
            scale_fill_igv()+
            xlab("")+
            ylab("Relative abundance")+
            labs(fill = "Genus")+
            theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
ggsave("figures/Barplot_Relative_abundance_top20_genus.pdf", p_genus, width = 15, height = 4)
```


# Alpha diversity (at species level)
```{r}
df_profile_copy <- df_profile
df_profile_copy$clade_name <- str_extract(df_profile_copy$clade_name, "s__[^|]+")

df_profile_t <- df_profile_copy %>% remove_rownames %>% column_to_rownames(var="clade_name") %>%
                  t() %>% as.data.frame()
alpha_shannon <- diversity(df_profile_t, index = "shannon") %>% as.data.frame() %>%
                  setNames("Shannon")
alpha_shannon$Samples <- rownames(alpha_shannon)
alpha_shannon_m <- merge(alpha_shannon, metadata, by="Samples", all.x = TRUE)

# calculate the mean and standard deviation of abudance, plus significance compared with DMSO
v_mean <- vector()
v_std <- vector()
v_sig <- vector()
types <- as.vector(unique(alpha_shannon_m$Group))
for (i in 1:length(types)) {
  v_mean[i] <- mean(alpha_shannon_m[alpha_shannon_m$Group==types[i],]$Shannon)
  v_std[i] <- sd(alpha_shannon_m[alpha_shannon_m$Group==types[i],]$Shannon)
  if(types[i] == "DMSO"){
    v_sig[i] <- NA
  }else{
    t_compare <- t.test(alpha_shannon_m[alpha_shannon_m$Group==types[i],]$Shannon, 
                        alpha_shannon_m[alpha_shannon_m$Group=="DMSO",]$Shannon, 
                        alternative = "two.sided", paired = FALSE)
    v_sig[i] <- t_compare$p.value
  }
}

df_shannon_m <- data.frame(Group=types,
                        v_mean=v_mean,
                        STD=v_std,
                        pvalues=v_sig)
df_shannon_m$sig_labels <- ifelse(df_shannon_m$pvalues<0.001, "***",
                                  ifelse(df_shannon_m$pvalues<0.01, "**",
                                         ifelse(df_shannon_m$pvalues<0.05, "*", "ns")))

df_shannon_m2 <- merge(df_shannon_m, unique(metadata[metadata$Mice=="IBD",c("Mice", "Concentration", "Group", "Peptide")]), all.x = FALSE)

# visualization
df_shannon_m2$Peptide <- factor(df_shannon_m2$Peptide,
                              levels = c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_shannon_m2$Concentration <- as.character(df_shannon_m2$Concentration)
df_shannon_m2$Concentration <- factor(df_shannon_m2$Concentration, levels = c("0.1", "1", "10"))

p_alpha <- ggplot(df_shannon_m2, aes(x=Concentration, y=v_mean, fill=Peptide)) + 
              geom_bar(position=position_dodge(), stat="identity", 
                       colour='black') + 
              geom_errorbar(aes(ymin=v_mean-STD, ymax=v_mean+STD), width=.2)+
              facet_grid(. ~ Peptide, scales = "free", space = "free")+
              theme_bw()+
              ylab("Shannon diversity index")+
              geom_text(aes(label = sig_labels), vjust = -1)+
              scale_fill_manual(values = c("#A0A0A0", "#555FAB", "#D03C32", "#759D59"))+
              theme(legend.position = "none")+
              ylim(0, 2.5)

ggsave("figures/Barplot_Shannon_diversity.pdf", p_alpha, width = 6, height = 4)
```



# Beta diversity (at species level)
```{r}
################################################################################
# PcoA
################################################################################
distance <- vegdist(df_profile_t, method = 'bray')
pcoa <- cmdscale(distance, k = (nrow(df_profile_t) - 1), eig = TRUE)

# check info
summary(pcoa)

# check the coordinate value
pcoa$eig
point <- data.frame(pcoa$point)

# compute first two coordinate value
pcoa_eig <- (pcoa$eig)[1:2] / sum(pcoa$eig)

# extract first two coordinate value
df_pca12 <- data.frame({pcoa$point})[1:2]
df_pca12$Samples <- rownames(df_pca12)
names(df_pca12)[1:2] <- c('PCoA1', 'PCoA2')

df_pca12 <- merge(df_pca12, metadata, by = 'Samples', all = FALSE)
df_pca12$Concentration <- as.character(df_pca12$Concentration)
df_pca12$Peptide <- factor(df_pca12$Peptide, 
                           levels = c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))

pcoa_p <- ggplot(df_pca12, aes(PCoA1, PCoA2, group = Peptide, color = Peptide)) +
        geom_point(aes(shape = Concentration), size = 2) + 
        # stat_ellipse(aes(group = interaction(Peptide, Concentration), 
        #            fill = Peptide, 
        #            color = Peptide), 
        #        alpha = 0.25, 
        #        level = 0.95,
        #        type = "norm",
        #        geom = "polygon") +
        # scale_shape_manual(values = c(17, 16, 15)) +
        ggforce::geom_mark_ellipse(aes(group = interaction(Peptide, Concentration),
                                       color = Peptide)) +
        scale_color_manual(values = c("#A0A0A0", "#555FAB", "#D03C32", "#759D59"))+
        labs(x = paste('PCo1: ', round(100 * pcoa_eig[1], 2), '%'),
             y = paste('PCo2: ', round(100 * pcoa_eig[2], 2), '%')) +
        theme(panel.grid=element_blank(), 
              panel.background = element_rect(color = 'black', fill = 'transparent', size = 1), 
              legend.key = element_rect(fill = 'transparent')) + 
        theme(axis.text = element_text(size = 10), axis.title = element_text(size = 12))+
        xlim(-0.1,0.25)+
        ylim(-0.1, 0.12)
ggsave("figures/Scatterplot_beta_diversity.pdf", pcoa_p, width = 6, height = 4)


# plot barplot for two axis
df_pca12$Peptide <- factor(df_pca12$Peptide,
                           levels = c("DMSO", "Vancomycin", "AIP_1", "AIP_2"))
df_pca12$Concentration <- factor(df_pca12$Concentration,
                                 levels = c("0.1", "1", "10"))

v_sig <- vector()
types <- as.vector(unique(df_pca12$Group))
for (i in 1:length(types)) {
  print(types[i])
    w_compare <- t.test(df_pca12[df_pca12$Group==types[i],]$PCoA1, 
                        df_pca12[df_pca12$Group=="DMSO",]$PCoA1, 
                        alternative = "two.sided", paired = FALSE)
    v_sig[i] <- w_compare$p.value
    
}
df_pvalue <- data.frame(Group=types,
                        pvalues=v_sig)
df_pca12_m <- merge(df_pca12, df_pvalue, by = "Group", all.x = TRUE)
df_pca12_m$sig_labels <- ifelse(df_pca12_m$pvalues<0.001, "***",
                                  ifelse(df_pca12_m$pvalues<0.01, "**",
                                         ifelse(df_pca12_m$pvalues<0.05, "*", "ns")))

p_pca1 <- ggplot(df_pca12_m, aes(x=Concentration, y=PCoA1, fill=Peptide)) + 
              geom_boxplot() + 
              facet_grid(. ~ Peptide, scales = "free", space = "free")+
              theme_bw()+
              ylab("PCo1 coordinates")+
              xlab("")+
              geom_text(aes(label = sig_labels), vjust = -1)+
              scale_fill_manual(values = c("#A0A0A0", "#555FAB", "#D03C32", "#759D59"))+
              theme(legend.position = "none")
ggsave("figures/Boxplot_Pco1_coordinates.pdf", p_pca1, width = 7, height = 3.5)


# Pco2
v_sig <- vector()
types <- as.vector(unique(df_pca12$Group))
for (i in 1:length(types)) {
    w_compare <- t.test(df_pca12[df_pca12$Group==types[i],]$PCoA2, 
                        df_pca12[df_pca12$Group=="DMSO",]$PCoA2, 
                        alternative = "two.sided", paired = FALSE)
    v_sig[i] <- w_compare$p.value
    
}
df_pvalue <- data.frame(Group=types,
                        pvalues=v_sig)
df_pca12_m <- merge(df_pca12, df_pvalue, by = "Group", all.x = TRUE)
df_pca12_m$sig_labels <- ifelse(df_pca12_m$pvalues<0.001, "***",
                                  ifelse(df_pca12_m$pvalues<0.01, "**",
                                         ifelse(df_pca12_m$pvalues<0.05, "*", "ns")))

p_pca2 <- ggplot(df_pca12_m, aes(x=Concentration, y=PCoA2, fill=Peptide)) + 
              geom_boxplot() + 
              facet_grid(. ~ Peptide, scales = "free", space = "free")+
              theme_bw()+
              ylab("PCo2 coordinates")+
              xlab("")+
              geom_text(aes(label = sig_labels), vjust = -1)+
              scale_fill_manual(values = c("#A0A0A0", "#555FAB", "#D03C32", "#759D59"))+
              theme(legend.position = "none")
ggsave("figures/Boxplot_Pco2_coordinates.pdf", p_pca2, width = 7, height = 3.5)


################################################################################
# Adonis2
################################################################################
metadata_s <- metadata %>% filter(Samples %in% rownames(df_profile_t))
metadata_s <- metadata_s %>% arrange(factor(Samples, levels = rownames(df_profile_t)))
identical(metadata_s$Samples, rownames(df_profile_t))

adonis_result <- adonis2(df_profile_t~Group, metadata_s, permutations = 999, distance = 'bray')
# save result
out_adonis2 <- data.frame(adonis_result, check.names = FALSE, stringsAsFactors = FALSE)
write.table(out_adonis2, file = 'tables/PERMANOVA.result_all_groups.txt', row.names = FALSE, sep = '\t', quote = FALSE, na = '')

# pairwise
group_name <- unique(metadata_s$Group)
adonis_result_two <- NULL
for (i in 1:(length(group_name) - 1)) {
  for (j in (i + 1):length(group_name)) {
    group_ij <- subset(metadata_s, Group %in% c(group_name[i], group_name[j]))
    otu_ij <- df_profile_t[group_ij$Samples, ]
    print(identical(group_ij$Samples, rownames(otu_ij)))
    adonis_result_otu_ij <- adonis2(otu_ij~Group, group_ij, permutations = 999, distance = 'bray')
    adonis_result_two <- rbind(adonis_result_two, 
                               unlist(c(paste(group_name[i], group_name[j], sep = '/'), 'Bray-Curtis', data.frame(adonis_result_otu_ij, check.names = FALSE)[1, ])))
  }
}
adonis_result_two <- data.frame(adonis_result_two, stringsAsFactors = FALSE)
names(adonis_result_two) <- c('Groups', 'Distance', 'Df', 'SumOfSqs',  'R2', 'F.Model', 'pvalues')
adonis_result_two$padjust <- p.adjust(adonis_result_two$pvalues, method = "fdr")

# marker significance
for (i in 1:nrow(adonis_result_two)) {
  if (adonis_result_two[i, "padjust"] <= 0.001) {adonis_result_two[i, 'Sig'] <- '***'}
  else if (adonis_result_two[i, 'padjust'] <= 0.01) {adonis_result_two[i, 'Sig'] <- '**'}
  else if (adonis_result_two[i, 'padjust'] <= 0.05) {adonis_result_two[i, 'Sig'] <- '*'}
}

# save result
write.table(adonis_result_two, 'tables/PERMANOVA.result_pairwise_999_all_groups.txt', row.names = FALSE, sep = '\t', quote = FALSE, na = '')


################################################################################
# Bray-Curtis dissimilarity
################################################################################
# df_bc <- as.matrix(distance) %>% reshape2::melt()
# df_bc <- df_bc[df_bc$Var1 != df_bc$Var2, ]
# df_bc_m <- merge(df_bc, metadata[,c("Samples", "Group")], by.x = "Var1", by.y = "Samples", all = FALSE)
# df_bc_m2 <- merge(df_bc_m, metadata[,c("Samples", "Group")], by.x = "Var2", by.y = "Samples", all = FALSE)
df_bc <- as.matrix(distance) %>% as.data.frame()
df_bc_m1 <- merge(df_bc, metadata[,c("Samples", "Group")], by.x=0, by.y="Samples", all.x=TRUE) %>%
            subset(select = -Row.names) %>% 
            aggregate(.~Group, mean) %>%
            remove_rownames() %>%
            column_to_rownames("Group")
df_bc_m2 <- df_bc_m1 %>% t() %>% as.data.frame()
df_bc_m2 <- merge(df_bc_m2, metadata[,c("Samples", "Group")], by.x=0, by.y="Samples", all.x=TRUE) %>%
            subset(select = -Row.names) %>% 
            aggregate(.~Group, mean) %>%
            remove_rownames() %>%
            column_to_rownames("Group")

# hcluster
dd <- dist(scale(df_bc_m2), method = "euclidean")
hc <- hclust(dd, method = "ward.D2")
plot(as.phylo(hc), cex = 0.6, label.offset = 0.5)

p_bc <- pheatmap(df_bc_m2)

ggsave("figures/Pheatmap_bray_curtis_distance.pdf", p_bc, width = 6, height = 5)
```



# Differential analysis
```{r}
# Wilcox analysis
all_groups <- unique(metadata_s$Group)
all_species <- colnames(df_profile_t)

f_compare <- function(group){
  df_abundance_com <- data.frame()
  for (species in all_species){
    group_1_species <- df_profile_t[metadata_s[metadata_s$Group=="DMSO", ]$Samples, species]
    group_2_species <- df_profile_t[metadata_s[metadata_s$Group==group, ]$Samples, species] 
    mean_DMSO <- mean(group_1_species)
    sd_DMSO <- sd(group_1_species)
    mean_group <- mean(group_2_species)
    sd_group <- sd(group_2_species)
    # Welch’s t-test
    w_compare <- t.test(group_1_species, group_2_species, 
                            alternative = "two.sided",
                        var.equal = FALSE, paired = FALSE)
    logFD <- log2((mean_group+0.001) / (mean_DMSO+0.001))
    sig <- w_compare$p.value
    df_temp <- data.frame(Species = species,
                          Mean_DMSO = mean_DMSO,
                          Sd_DMSO = sd_DMSO,
                          Mean_group = mean_group,
                          Sd_group = sd_group,
                          pvalues = sig,
                          log2FD = logFD)
    df_abundance_com <- rbind(df_abundance_com, df_temp)
  }
  df_abundance_com$padjust <- p.adjust(df_abundance_com$pvalues, method = "BH")
  return(df_abundance_com)
}

daa_van_0.1 <- f_compare("Vancomycin-0.1")
daa_van_1 <- f_compare("Vancomycin-1")
daa_van_10 <- f_compare("Vancomycin-10")
daa_AIP1_0.1 <- f_compare("AIP_1-0.1")
daa_AIP1_1 <- f_compare("AIP_1-1")
daa_AIP1_10 <- f_compare("AIP_1-10")
daa_AIP2_0.1 <- f_compare("AIP_2-0.1")
daa_AIP2_1 <- f_compare("AIP_2-1")
daa_AIP2_10 <- f_compare("AIP_2-10")


# Differential species number (|log2FD| > 1 & padjust < 0.05)
c_van_0.1 <- daa_van_0.1 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_van_1 <- daa_van_1 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_van_10 <- daa_van_10 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP1_0.1 <- daa_AIP1_0.1 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP1_1 <- daa_AIP1_1 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP1_10 <- daa_AIP1_10 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP2_0.1 <- daa_AIP2_0.1 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP2_1 <- daa_AIP2_1 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP2_10 <- daa_AIP2_10 %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()



### Masslin2 analysis
f_maaslin2 <- function(group){
  meta_select <- metadata %>% filter(Group %in% c("DMSO", group))
  df_profile_t_select <- df_profile_t[meta_select$Samples, ]
  df_profile_t_select <- df_profile_t_select[, colSums(df_profile_t_select)>0]
  
  fit_data <- Maaslin2(
            input_data = df_profile_t_select, 
            input_metadata = meta_select, 
            output = paste("Maaslin2/",group,sep = ""), 
            fixed_effects = "Group",
            cores = 10,
            reference = "DMSO",
            max_significance = 0.05)
  res <- fit_data$results
  return(res)
}

maas_van_0.1 <- f_maaslin2("Vancomycin-0.1")
maas_van_1 <- f_maaslin2("Vancomycin-1")
maas_van_10 <- f_maaslin2("Vancomycin-10")
maas_AIP1_0.1 <- f_maaslin2("AIP_1-0.1")
maas_AIP1_1 <- f_maaslin2("AIP_1-1")
maas_AIP1_10 <- f_maaslin2("AIP_1-10")
maas_AIP2_0.1 <- f_maaslin2("AIP_2-0.1")
maas_AIP2_1 <- f_maaslin2("AIP_2-1")
maas_AIP2_10 <- f_maaslin2("AIP_2-10")

# add foldchange
maas_van_0.1_m <- merge(maas_van_0.1, 
                        daa_van_0.1[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_van_1_m <- merge(maas_van_1, 
                        daa_van_1[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_van_10_m <- merge(maas_van_10, 
                        daa_van_10[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_AIP1_0.1_m <- merge(maas_AIP1_0.1, 
                        daa_AIP1_0.1[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_AIP1_1_m <- merge(maas_AIP1_1, 
                        daa_AIP1_1[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_AIP1_10_m <- merge(maas_AIP1_10, 
                        daa_AIP1_10[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_AIP2_0.1_m <- merge(maas_AIP2_0.1, 
                        daa_AIP2_0.1[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_AIP2_1_m <- merge(maas_AIP2_1, 
                        daa_AIP2_1[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)
maas_AIP2_10_m <- merge(maas_AIP2_10, 
                        daa_AIP2_10[,c("Species","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Species", all.x = TRUE)


# plot number of significantly differential species
df_diff <- data.frame("Vancomycin-0.1" = sum(maas_van_0.1$qval<0.05),
                      "Vancomycin-1" = sum(maas_van_1$qval<0.05),
                      "Vancomycin-10" = sum(maas_van_10$qval<0.05),
                      "AIP_1-0.1" = sum(maas_AIP1_0.1$qval<0.05),
                      "AIP_1-1" = sum(maas_AIP1_1$qval<0.05),
                      "AIP_1-10" = sum(maas_AIP1_10$qval<0.05),
                      "AIP_2-0.1" = sum(maas_AIP2_0.1$qval<0.05),
                      "AIP_2-1" = sum(maas_AIP2_1$qval<0.05),
                      "AIP_2-10" = sum(maas_AIP2_10$qval<0.05),
                      check.names = FALSE)
df_diff <- df_diff %>% t() %>% as.data.frame()
df_diff$group <- rownames(df_diff)
df_diff$group <- factor(df_diff$group, levels = df_diff$group)

p_diff <- ggplot(data=df_diff, aes(x=group, y=V1)) +
          geom_bar(stat="identity")+
          theme_bw()+
          xlab("")+
          ylab("Number of significantly differential species")+
          theme(axis.text.x = element_text(angle = 45, colour = "black", hjust = 1))

ggsave("figures/Barplot_Number_of_differential_species.pdf", p_diff, width = 6, height = 4)



# upsetR for visualizing the intersection of differentially abundance species
listinput_up <- list(van_0.1 = maas_van_0.1[maas_van_0.1$qval<0.05 & maas_van_0.1$coef > 0,]$feature, 
                    van_1 = maas_van_1[maas_van_1$qval<0.05 & maas_van_1$coef > 0,]$feature, 
                    van_10 = maas_van_10[maas_van_10$qval<0.05 & maas_van_10$coef > 0,]$feature,
                    AIP1_0.1 = maas_AIP1_0.1[maas_AIP1_0.1$qval<0.05 & maas_AIP1_0.1$coef < 0,]$feature,
                    AIP1_1 = maas_AIP1_1[maas_AIP1_1$qval<0.05 & maas_AIP1_1$coef < 0,]$feature,
                    AIP1_10 = maas_AIP1_10[maas_AIP1_10$qval<0.05 & maas_AIP1_10$coef < 0,]$feature,
                    AIP2_0.1 = maas_AIP2_0.1[maas_AIP2_0.1$qval<0.05 & maas_AIP2_0.1$coef < 0,]$feature,
                    AIP2_1 = maas_AIP2_1[maas_AIP2_1$qval<0.05 & maas_AIP2_1$coef < 0,]$feature,
                    AIP2_10 = maas_AIP2_10[maas_AIP2_10$qval<0.05 & maas_AIP2_10$coef < 0,]$feature)
listinput_down <- list(van_0.1 = maas_van_0.1[maas_van_0.1$qval<0.05 & maas_van_0.1$coef < 0,]$feature, 
                    van_1 = maas_van_1[maas_van_1$qval<0.05 & maas_van_1$coef < 0,]$feature, 
                    van_10 = maas_van_10[maas_van_10$qval<0.05 & maas_van_10$coef < 0,]$feature,
                    AIP1_0.1 = maas_AIP1_0.1[maas_AIP1_0.1$qval<0.05 & maas_AIP1_0.1$coef > 0,]$feature,
                    AIP1_1 = maas_AIP1_1[maas_AIP1_1$qval<0.05 & maas_AIP1_1$coef > 0,]$feature,
                    AIP1_10 = maas_AIP1_10[maas_AIP1_10$qval<0.05 & maas_AIP1_10$coef > 0,]$feature,
                    AIP2_0.1 = maas_AIP2_0.1[maas_AIP2_0.1$qval<0.05 & maas_AIP2_0.1$coef > 0,]$feature,
                    AIP2_1 = maas_AIP2_1[maas_AIP2_1$qval<0.05 & maas_AIP2_1$coef > 0,]$feature,
                    AIP2_10 = maas_AIP2_10[maas_AIP2_10$qval<0.05 & maas_AIP2_10$coef > 0,]$feature)

p_up <- upset(fromList(listinput_up), order.by = "freq")
p_down <- upset(fromList(listinput_down), order.by = "freq")

pdf(file = "figures/UpsetR_Intersection_differentially_UP_species.pdf", height = 4, width = 5)
p_up
grid.text("Up", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))
dev.off()
pdf(file = "figures/UpsetR_Intersection_differentially_Down_species.pdf", height = 4, width = 5)
p_down
grid.text("Down", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))
dev.off()


### heatmap plot for significantly differential species
d_AIP_1_10 <- maas_AIP1_10 %>% filter(qval < 0.05)
d_AIP_2_0.1 <- maas_AIP2_0.1 %>% filter(qval < 0.05)
d_AIP_2_10 <- maas_AIP2_10 %>% filter(qval < 0.05)

all_significant_species <- Reduce(union, list(d_AIP_1_10$feature, d_AIP_2_0.1$feature, d_AIP_2_10$feature))

maas_van_0.1_s <- maas_van_0.1_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_van_0.1", "qval_van_0.1"))
maas_van_1_s <- maas_van_1_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_van_1", "qval_van_1"))
maas_van_10_s <- maas_van_10_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_van_10", "qval_van_10"))
maas_AIP1_0.1_s <- maas_AIP1_0.1_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP1_0.1", "qval_AIP1_0.1"))
maas_AIP1_1_s <- maas_AIP1_1_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP1_1", "qval_AIP1_1"))
maas_AIP1_10_s <- maas_AIP1_10_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP1_10", "qval_AIP1_10"))
maas_AIP2_0.1_s <- maas_AIP2_0.1_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP2_0.1", "qval_AIP2_0.1"))
maas_AIP2_1_s <- maas_AIP2_1_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP2_1", "qval_AIP2_1"))
maas_AIP2_10_s <- maas_AIP2_10_m %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP2_10", "qval_AIP2_10"))

df_featuers <- Reduce(function(x,y){merge(x,y,by="feature",all=TRUE)},
                      list(maas_van_0.1_s, maas_van_1_s, maas_van_10_s,
                           maas_AIP1_0.1_s, maas_AIP1_1_s, maas_AIP1_10_s,
                           maas_AIP2_0.1_s, maas_AIP2_1_s, maas_AIP2_10_s))
write.csv(df_featuers, file = "tables/Significantly_differential_species.csv")


df_feature_coef <- df_featuers %>% select(c("feature", "log2FD_van_0.1", "log2FD_van_1", "log2FD_van_10",
                                            "log2FD_AIP1_0.1", "log2FD_AIP1_1", "log2FD_AIP1_10", 
                                            "log2FD_AIP2_0.1", "log2FD_AIP2_1", "log2FD_AIP2_10")) %>%
                    remove_rownames() %>% column_to_rownames("feature") %>%
                    setNames(c("Van-0.1", "Van-1", "Van-10",
                               "AIP_1-0.1", "AIP_1-1", "AIP_1-10", 
                               "AIP_2-0.1", "AIP_2-1", "AIP_2-10"))
df_feature_qval <- df_featuers %>% select(c("feature", "qval_van_0.1", "qval_van_1", "qval_van_10",
                                            "qval_AIP1_0.1", "qval_AIP1_1", "qval_AIP1_10", 
                                            "qval_AIP2_0.1", "qval_AIP2_1", "qval_AIP2_10")) %>%
                    remove_rownames() %>% column_to_rownames("feature") %>%
                    setNames(c("Van-0.1", "Van-1", "Van-10",
                               "AIP_1-0.1", "AIP_1-1", "AIP_1-10", 
                               "AIP_2-0.1", "AIP_2-1", "AIP_2-10"))


pdf(file = "figures/Heatmap_differential_species.pdf",height = 12,width = 8)
Heatmap(as.matrix(df_feature_coef), name = "log2FD", 
        col = colorRamp2(c(min(df_feature_coef), 0, max(df_feature_coef)),c("#0072B5CC", "#FFFFFF", "#E18727CC")), column_dend_height = unit(10, "mm"),
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "complete",
        show_row_dend = FALSE,
        show_column_dend = FALSE,
        row_names_gp = gpar(fontsize=10),
        column_names_gp = gpar(fontsize=12),
        cluster_columns = FALSE,
        cluster_rows = TRUE,
        row_title_side = "left",row_dend_side="left",
        row_names_side = "left", column_names_rot = 45,
        cell_fun = function(j, i, x, y, w, h, fill) {
          if(df_feature_qval[i, j] < 0.001) {
            grid.text("***", x, y)
          } else if(df_feature_qval[i, j] < 0.01) {
            grid.text("**", x, y)
          } else if(df_feature_qval[i, j] < 0.05) {
            grid.text("*", x, y)
          }
        })
dev.off()






################################################################################
# Genus level
################################################################################
df_profile_g <- df_profile %>% select(c("clade_name", metadata[metadata$Mice=="IBD", ]$Samples))
df_profile_g$clade_name <- str_extract(df_profile_g$clade_name, "g__[^|]+")
df_profile_g <- aggregate(.~clade_name, df_profile_g, sum) %>%
                remove_rownames() %>% column_to_rownames("clade_name") %>%
                t() %>% as.data.frame()

all_genera <- colnames(df_profile_g)
f_compare_genus <- function(group){
  df_abundance_com <- data.frame()
  for (genus in all_genera){
    group_1_genus <- df_profile_g[metadata_s[metadata_s$Group=="DMSO", ]$Samples, genus]
    group_2_genus <- df_profile_g[metadata_s[metadata_s$Group==group, ]$Samples, genus] 
    mean_DMSO <- mean(group_1_genus)
    sd_DMSO <- sd(group_1_genus)
    mean_group <- mean(group_2_genus)
    sd_group <- sd(group_2_genus)
    # Welch’s t-test
    w_compare <- t.test(group_1_genus, group_2_genus, 
                            alternative = "two.sided", , var.equal = FALSE, paired = FALSE)
    logFD <- log2((mean_group+0.001) / (mean_DMSO+0.001))
    sig <- w_compare$p.value
    df_temp <- data.frame(Genera = genus,
                          Mean_DMSO = mean_DMSO,
                          Sd_DMSO = sd_DMSO,
                          Mean_group = mean_group,
                          Sd_group = sd_group,
                          pvalues = sig,
                          log2FD = logFD)
    df_abundance_com <- rbind(df_abundance_com, df_temp)
  }
  df_abundance_com$padjust <- p.adjust(df_abundance_com$pvalues, method = "BH")
  return(df_abundance_com)
}

daa_van_0.1_g <- f_compare_genus("Vancomycin-0.1")
daa_van_1_g <- f_compare_genus("Vancomycin-1")
daa_van_10_g <- f_compare_genus("Vancomycin-10")
daa_AIP_1_0.1_g <- f_compare_genus("AIP_1-0.1")
daa_AIP_1_1_g <- f_compare_genus("AIP_1-1")
daa_AIP_1_10_g <- f_compare_genus("AIP_1-10")
daa_AIP_2_0.1_g <- f_compare_genus("AIP_2-0.1")
daa_AIP_2_1_g <- f_compare_genus("AIP_2-1")
daa_AIP_2_10_g <- f_compare_genus("AIP_2-10")


# Differential species number (|log2FD| > 1 & padjust < 0.05)
c_van_0.1_g <- daa_van_0.1_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_van_1_g <- daa_van_1_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_van_10_g <- daa_van_10_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP_1_0.1_g <- daa_AIP_1_0.1_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP_1_1_g <- daa_AIP_1_1_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP_1_10_g <- daa_AIP_1_10_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP_2_0.1_g <- daa_AIP_2_0.1_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP_2_1_g <- daa_AIP_2_1_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()
c_AIP_2_10_g <- daa_AIP_2_10_g %>% filter(abs(log2FD) > 1 & padjust < 0.05) %>% na.omit()

### Masslin2 analysis
f_maaslin2_g <- function(group){
  meta_select <- metadata %>% filter(Group %in% c("DMSO", group))
  df_profile_t_select <- df_profile_g[meta_select$Samples, ]
  df_profile_t_select <- df_profile_t_select[, colSums(df_profile_t_select)>0]
  
  fit_data <- Maaslin2(
            input_data = df_profile_t_select, 
            input_metadata = meta_select, 
            output = paste("Maaslin2_genus/",group,sep = ""), 
            fixed_effects = "Group",
            cores = 10,
            reference = "DMSO",
            max_significance = 0.05)
  res <- fit_data$results
  return(res)
}

maas_van_0.1_g <- f_maaslin2_g("Vancomycin-0.1")
maas_van_1_g <- f_maaslin2_g("Vancomycin-1")
maas_van_10_g <- f_maaslin2_g("Vancomycin-10")
maas_AIP_1_0.1_g <- f_maaslin2_g("AIP_1-0.1")
maas_AIP_1_1_g <- f_maaslin2_g("AIP_1-1")
maas_AIP_1_10_g <- f_maaslin2_g("AIP_1-10")
maas_AIP_2_0.1_g <- f_maaslin2_g("AIP_2-0.1")
maas_AIP_2_1_g <- f_maaslin2_g("AIP_2-1")
maas_AIP_2_10_g <- f_maaslin2_g("AIP_2-10")

# add foldchange
maas_van_0.1_mg <- merge(maas_van_0.1_g, 
                        daa_van_0.1_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_van_1_mg <- merge(maas_van_1_g, 
                        daa_van_1_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_van_10_mg <- merge(maas_van_10_g, 
                        daa_van_10_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_AIP_1_0.1_mg <- merge(maas_AIP_1_0.1_g, 
                        daa_AIP_1_0.1_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_AIP_1_1_mg <- merge(maas_AIP_1_1_g, 
                        daa_AIP_1_1_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_AIP_1_10_mg <- merge(maas_AIP1_10_g, 
                        daa_AIP_1_10_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_AIP_2_0.1_mg <- merge(maas_AIP2_0.1_g, 
                        daa_AIP_2_0.1_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_AIP_2_1_mg <- merge(maas_AIP_2_1_g, 
                        daa_AIP_2_1_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)
maas_AIP_2_10_mg <- merge(maas_AIP_2_10_g, 
                        daa_AIP_2_10_g[,c("Genera","Mean_DMSO","Sd_DMSO","Mean_group","Sd_group","log2FD")],
                        by.x = "feature", by.y = "Genera", all.x = TRUE)


# plot number of significantly differential species
df_diff_g <- data.frame("Vancomycin-0.1" = sum(maas_van_0.1_g$qval<0.05),
                      "Vancomycin-1" = sum(maas_van_1_g$qval<0.05),
                      "Vancomycin-10" = sum(maas_van_10_g$qval<0.05),
                      "AIP_1-0.1" = sum(maas_AIP_1_0.1_g$qval<0.05),
                      "AIP_1-1" = sum(maas_AIP_1_1_g$qval<0.05),
                      "AIP_1-10" = sum(maas_AIP_1_10_g$qval<0.05),
                      "AIP_2-0.1" = sum(maas_AIP_2_0.1_g$qval<0.05),
                      "AIP_2-1" = sum(maas_AIP_2_1_g$qval<0.05),
                      "AIP_2-10" = sum(maas_AIP_2_10_g$qval<0.05),
                      check.names = FALSE)
df_diff_g <- df_diff_g %>% t() %>% as.data.frame()
df_diff_g$group <- rownames(df_diff_g)
df_diff_g$group <- factor(df_diff_g$group, levels = df_diff_g$group)

p_diff <- ggplot(data=df_diff_g, aes(x=group, y=V1)) +
          geom_bar(stat="identity")+
          theme_bw()+
          xlab("")+
          ylab("Number of significantly differential species")+
          theme(axis.text.x = element_text(angle = 45, colour = "black", hjust = 1))

ggsave("figures/Barplot_Number_of_differential_genus.pdf", p_diff, width = 6, height = 4)



# upsetR for visualizing the intersection of differentially abundance species
listinput_up_g <- list(van_0.1 = maas_van_0.1_g[maas_van_0.1_g$qval<0.05 & maas_van_0.1_g$coef > 0,]$feature, 
                    van_1 = maas_van_1_g[maas_van_1_g$qval<0.05 & maas_van_1_g$coef > 0,]$feature, 
                    van_10 = maas_van_10_g[maas_van_10_g$qval<0.05 & maas_van_10_g$coef > 0,]$feature,
                    AIP1_0.1 = maas_AIP1_0.1_g[maas_AIP1_0.1_g$qval<0.05 & maas_AIP1_0.1_g$coef < 0,]$feature,
                    AIP1_1 = maas_AIP1_1_g[maas_AIP1_1_g$qval<0.05 & maas_AIP1_1_g$coef < 0,]$feature,
                    AIP1_10 = maas_AIP1_10_g[maas_AIP1_10_g$qval<0.05 & maas_AIP1_10_g$coef < 0,]$feature,
                    AIP2_0.1 = maas_AIP2_0.1_g[maas_AIP2_0.1_g$qval<0.05 & maas_AIP2_0.1_g$coef < 0,]$feature,
                    AIP2_1 = maas_AIP2_1_g[maas_AIP2_1_g$qval<0.05 & maas_AIP2_1_g$coef < 0,]$feature,
                    AIP2_10 = maas_AIP2_10_g[maas_AIP2_10_g$qval<0.05 & maas_AIP2_10_g$coef < 0,]$feature)
listinput_down_g <- list(van_0.1 = maas_van_0.1_g[maas_van_0.1_g$qval<0.05 & maas_van_0.1_g$coef < 0,]$feature, 
                    van_1 = maas_van_1_g[maas_van_1_g$qval<0.05 & maas_van_1_g$coef < 0,]$feature, 
                    van_10 = maas_van_10_g[maas_van_10_g$qval<0.05 & maas_van_10_g$coef < 0,]$feature,
                    AIP1_0.1 = maas_AIP1_0.1_g[maas_AIP1_0.1_g$qval<0.05 & maas_AIP1_0.1_g$coef > 0,]$feature,
                    AIP1_1 = maas_AIP1_1_g[maas_AIP1_1_g$qval<0.05 & maas_AIP1_1_g$coef > 0,]$feature,
                    AIP1_10 = maas_AIP1_10_g[maas_AIP1_10_g$qval<0.05 & maas_AIP1_10_g$coef > 0,]$feature,
                    AIP2_0.1 = maas_AIP2_0.1_g[maas_AIP2_0.1_g$qval<0.05 & maas_AIP2_0.1_g$coef > 0,]$feature,
                    AIP2_1 = maas_AIP2_1_g[maas_AIP2_1_g$qval<0.05 & maas_AIP2_1_g$coef > 0,]$feature,
                    AIP2_10 = maas_AIP2_10_g[maas_AIP2_10_g$qval<0.05 & maas_AIP2_10_g$coef > 0,]$feature)

p_up_g <- upset(fromList(listinput_up_g), order.by = "freq")
p_down_g <- upset(fromList(listinput_down_g), order.by = "freq")

pdf(file = "figures/UpsetR_Intersection_differentially_UP_genus.pdf", height = 4, width = 5)
p_up_g
grid.text("Up", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))
dev.off()
pdf(file = "figures/UpsetR_Intersection_differentially_Down_genus.pdf", height = 4, width = 5)
p_down_g
grid.text("Down", x = 0.65, y = 0.95, gp = gpar(fontsize = 20))
dev.off()


### heatmap plot for significantly differential species
d_AIP_1_10_g <- maas_AIP1_10_g %>% filter(qval < 0.05)
d_AIP_2_0.1_g <- maas_AIP2_0.1_g %>% filter(qval < 0.05)
d_AIP_2_10_g <- maas_AIP2_10_g %>% filter(qval < 0.05)

all_significant_species <- Reduce(union, list(d_AIP_1_10_g$feature, d_AIP_2_0.1_g$feature, d_AIP_2_10_g$feature))

maas_van_0.1_sg <- maas_van_0.1_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_van_0.1", "qval_van_0.1"))
maas_van_1_sg <- maas_van_1_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_van_1", "qval_van_1"))
maas_van_10_sg <- maas_van_10_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_van_10", "qval_van_10"))
maas_AIP1_0.1_sg <- maas_AIP_1_0.1_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP1_0.1", "qval_AIP1_0.1"))
maas_AIP1_1_sg <- maas_AIP_1_1_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP1_1", "qval_AIP1_1"))
maas_AIP1_10_sg <- maas_AIP_1_10_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP1_10", "qval_AIP1_10"))
maas_AIP2_0.1_sg <- maas_AIP_2_0.1_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP2_0.1", "qval_AIP2_0.1"))
maas_AIP2_1_sg <- maas_AIP_2_1_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP2_1", "qval_AIP2_1"))
maas_AIP2_10_sg <- maas_AIP_2_10_mg %>% filter(feature %in% all_significant_species) %>%
                    select(c("feature", "log2FD", "qval")) %>%
                    setNames(c("feature", "log2FD_AIP2_10", "qval_AIP2_10"))

df_featuers_g <- Reduce(function(x,y){merge(x,y,by="feature",all=TRUE)},
                      list(maas_van_0.1_sg, maas_van_1_sg, maas_van_10_sg,
                           maas_AIP1_0.1_sg, maas_AIP1_1_sg, maas_AIP1_10_sg,
                           maas_AIP2_0.1_sg, maas_AIP2_1_sg, maas_AIP2_10_sg))
write.csv(df_featuers_g, file = "tables/Significantly_differential_genus.csv")


df_feature_coef_g <- df_featuers_g %>% select(c("feature", "log2FD_van_0.1", "log2FD_van_1", "log2FD_van_10",
                                                "log2FD_AIP1_0.1", "log2FD_AIP1_1", "log2FD_AIP1_10", 
                                                "log2FD_AIP2_0.1", "log2FD_AIP2_1", "log2FD_AIP2_10")) %>%
                    remove_rownames() %>% column_to_rownames("feature") %>%
                    setNames(c("Van_0.1", "Van_1", "Van_10",
                               "AIP_1-0.1", "AIP_1-1", "AIP_1-10", 
                               "AIP_2-0.1", "AIP_2-1", "AIP_2-10"))
df_feature_qval_g <- df_featuers_g %>% select(c("feature", "qval_van_0.1", "qval_van_1", "qval_van_10", 
                                                "qval_AIP1_0.1", "qval_AIP1_1", "qval_AIP1_10", 
                                                "qval_AIP2_0.1", "qval_AIP2_1", "qval_AIP2_10")) %>%
                    remove_rownames() %>% column_to_rownames("feature") %>%
                    setNames(c("Van_0.1", "Van_1", "Van_10",
                               "AIP_1-0.1", "AIP_1-1", "AIP_1-10", 
                               "AIP_2-0.1", "AIP_2-1", "AIP_2-10"))


pdf(file = "figures/Heatmap_differential_genus.pdf",height = 8,width = 8)
Heatmap(as.matrix(df_feature_coef_g), name = "log2FD", 
        col = colorRamp2(c(min(df_feature_coef_g), 0, max(df_feature_coef_g)),c("#0072B5CC", "#FFFFFF", "#E18727CC")), column_dend_height = unit(10, "mm"),
        clustering_distance_rows = "euclidean",
        clustering_method_rows = "complete",
        show_row_dend = FALSE,
        show_column_dend = FALSE,
        row_names_gp = gpar(fontsize=10),
        column_names_gp = gpar(fontsize=12),
        cluster_columns = FALSE,
        cluster_rows = TRUE,
        row_title_side = "left",row_dend_side="left",
        row_names_side = "left", column_names_rot = 45,
        cell_fun = function(j, i, x, y, w, h, fill) {
          if(df_feature_qval_g[i, j] < 0.001) {
            grid.text("***", x, y)
          } else if(df_feature_qval_g[i, j] < 0.01) {
            grid.text("**", x, y)
          } else if(df_feature_qval_g[i, j] < 0.05) {
            grid.text("*", x, y)
          }
        })
dev.off()
```



# visulaize species abudance
```{r}
select_species <- c( "s__Paramuribaculum_intestinale", "s__Oscillospiraceae_bacterium", "s__Heminiphilus_faecis", "s__Prevotella_sp_MGM1")

df_species_show <- df_profile_t[,select_species]
df_species_show <- df_species_show %>% mutate(Samples=rownames(df_species_show))
df_species_show_m <- merge(df_species_show, metadata[,c("Samples", "Group")], by="Samples", all.x = TRUE)
df_species_show_m <- df_species_show_m %>% filter(Group %in% c("DMSO", "Vancomycin-10", "AIP_1-10", "AIP_2-10"))
df_species_show_m <- df_species_show_m[,colnames(df_species_show_m)!="Samples"]
df_species_show_melt <- reshape2::melt(df_species_show_m, id.vars="Group")
df_species_show_melt$Group <- factor(df_species_show_melt$Group,
                                     levels = c("DMSO", "Vancomycin-10", "AIP_1-10", "AIP_2-10"))

p <- ggplot(df_species_show_melt, aes(x=Group, y=value, fill=Group)) + 
      geom_boxplot() + 
      geom_jitter(position = "jitter") + 
      scale_fill_manual(values = c("#A0A0A0", "#555FAB", "#D03C32", "#759D59"))+
      facet_wrap(.~variable, scales = "free_y", nrow = 1) +
      theme_bw()+
      labs(x = "", y = "Relative abundance")+
      theme(legend.position = "none")+
      stat_compare_means(ref.group = "DMSO", method = "t.test", label = "p.signif")+
      theme(axis.text.x = element_text(angle = 45, colour = "black", hjust = 1))
ggsave("figures/Boxplot_abundance.pdf", p, width = 12, height = 3)
```

